export const FoodInitialData = [
    {
      "name": "Rujak Buah",
      "image": "/image/1.jpg",
      "description": "Rujak Buah adalah salad buah tradisional yang berasal dari Jawa. Terbuat dari potongan buah-buahan segar yang disajikan dengan sambal rujak yang pedas, membuat Rujak Buah menjadi cemilan yang bisa dinikmati kapanpun dan dimanapun.",
      "amount": 2,
      "typeOfAmount": "buah/pcs",
      "expiration": "12/07/2022",
      "type": [
        "Makanan Berat"
      ],
      "address": "Jl. Bumi Marina Emas Utara No.II",
      "city": "Surabaya",
      "user": "Lathifa Itqon",
      "wa": "628113399490",
      "id": "1"
    },
    {
      "name": "Teh Botol Sosro",
      "image": "/image/2.jpg",
      "description": "Minuman teh dalam kemasan, disumbangkan karena stock masih banyak dan akan expire",
      "amount": 5,
      "typeOfAmount": "kardus",
      "expiration": "15/08/2022",
      "type": [
        "Minuman"
      ],
      "address": "Jl. Mangun Jaya 957-958",
      "city": "Palembang",
      "user": "Prema Dananjaya",
      "wa": "6285829139939",
      "id": "2"
    },
    {
      "name": "Buah Naga Merah",
      "image": "/image/3.jpg",
      "description": "Buah naga merah hasil memetik dari kebun sendiri, masih segar. Bisa ambil sepuasnya gratis.",
      "amount": 100,
      "typeOfAmount": "buah/pcs",
      "expiration": "18/07/2022",
      "type": ["Buah/Sayuran"],
      "address": "Jl. Plaosan Bar. No.49",
      "city": "Malang",
      "user": "Ulil Albab",
      "wa": "6285156472966",
      "id": "3"
    },
    {
      "name": "Nasi Padang",
      "image": "/image/4.jpg",
      "description": "Nasi padang dengan beraneka macam lauk yang dapat anda pilih langsung, silahkan ambil gratis.",
      "amount": 50,
      "typeOfAmount": "buah/pcs",
      "expiration": "10/07/2022",
      "type": ["Makanan Berat"],
      "address": "Jl. Sunan Ampel No.2",
      "city": "Kediri",
      "user": "Riyaldi Putra",
      "wa": "6281337318957",
      "id": "4"
    },
    {
      "name": "Coklat SilverQueen",
      "image": "/image/5.jpg",
      "description": "Expired dalam 2 bulan kedepan, stock masih banyak silahkan diambil. Tersedia varian almond, mente, milk.",
      "amount": 10,
      "typeOfAmount": "kardus",
      "expiration": "10/09/2022",
      "type": ["Makanan Ringan"],
      "address": "Jl. Garut No.8",
      "city": "Bandung",
      "user": "Diah Ayu",
      "wa": "6281283380927",
      "id": "5"
    },
    {
      "name": "Chitato Barbeque",
      "image": "/image/6.jpg",
      "description": "Keripik kentang berperasa barbeque, cocok untuk dimakan bersama teman-teman, stock berlebih sehingga dibagikan.",
      "amount": 20,
      "typeOfAmount": "buah/pcs",
      "expiration": "10/10/2023",
      "type": ["Makanan ringan"],
      "address": "Jl. Kemang V B No.32",
      "city": "Jakarta",
      "user": "Rani Sheryl",
      "wa": "62812345678",
      "id": "6"
    },
    {
      "name": "Susu Ultramilk UHT",
      "image": "/image/7.jpg",
      "description": "Stock berlebih silahkan diambil",
      "amount": 50,
      "typeOfAmount": "buah/pcs",
      "expiration": "20/02/2022",
      "type": ["Minuman"],
      "address": "Jl. Arif Rahman Hakim No.10",
      "city": "Surabaya",
      "user": "Dimas Sucahyo",
      "wa": "62812345678",
      "id": "7"
    },
    {
      "name": "Kue Putri Salju",
      "image": "/image/8.jpg",
      "description": "Kue khas lebaran, dibuat sendiri dengan bahan yang berkualitas. Dibagikan secara gratis karena keleihan produksi.",
      "amount": 10,
      "typeOfAmount": "Lusin",
      "expiration": "08/08/2022",
      "type": ["Makanan Ringan"],
      "address": "Jl. Teknik Komputer IV No.54",
      "city": "Surabaya",
      "user": "Nevin Arifin",
      "wa": "62812345678",
      "id": "8"
    },
    {
      "name": "Penyetan Ayam",
      "image": "/image/9.jpg",
      "description": "Spesial setaip hari senin dan kamis, dibagikan secara gratis. Silahkan dipilih lauk maupun sayur dengan bebas selama masih tersedia.",
      "amount": 100,
      "typeOfAmount": "buah/pcs",
      "expiration": "10/07/2022",
      "type": ["Makanan Berat"],
      "address": "Jl. Sememi Rejo Asri No.1",
      "city": "Surabaya",
      "user": "Rumah Penyetan",
      "wa": "62812345678",
      "id": "9"
    },
    {
      "name": "Sayur Bayam",
      "image": "/image/10.jpg",
      "description": "Sedang panen besar, silahkan diambil bagi yang membutuhkan",
      "amount": 10,
      "typeOfAmount": "buah/pcs",
      "expiration": "10/07/2022",
      "type": ["Buah/Sayur"],
      "address": "Desa Sumberejo No.5 Gg. Pangkur",
      "city": "Batu",
      "user": "Kebun MbokDe",
      "wa": "62812345678",
      "id": "10"
    }
  ]